name: sspd_work1

services:
  db:
    image: mysql # образ MySQL
    restart: always
    #
    command: --default-authentication-plugin=mysql_native_password #драйвера
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - sspd_work1:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web_server:
    build:
      dockerfile: dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
      #
    volumes:
      - ./www:/var/www/html:rw

volumes:
  sspd_work1: